// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epgifclglrrgzpguqbde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwZ2lmY2xnbHJyZ3pwZ3VxYmRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNjI2MzMsImV4cCI6MjA3MjkzODYzM30.q4EGEYrHOOH-mmHL-3PvJNOw9gz8a0Fm0no44qQ61dI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});